export const GalleryItems = [
    { image: "/Fotky/hero/hero-1.avif", },
    { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-1.avif" },
    { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-2.avif" },
    { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-3.avif" },
    { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-4.avif" },
    { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-5.avif" },
    { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-5.avif" },
    { image: "/Fotky/malovani-detskeho-pokoje/malovani-detskeho-pokoje-2.avif" },
    // { image: "/Fotky/Malovani (2).jpg" },
    // { image: "/Fotky/Malovani (3).jpg" },
    // { image: "/Fotky/Malovani (4).jpg" },
    // { image: "/Fotky/Malovani na klic (1).jpg" },
    // { image: "/Fotky/Malovani na klic (2).jpg" },
    // { image: "/Fotky/Malovani na klic (3).jpg" },
    // { image: "/Fotky/Malovani na klic (4).jpg" },
    // { image: "/Fotky/Malovani na klic (5).jpg" },
    // { image: "/Fotky/Nater dveri (1).jpg" },
    // { image: "/Fotky/Nater oken (1).jpg" },
    // { image: "/Fotky/Natery fasad (5).jpg" },
    // { image: "/Fotky/Natery fasad (7).jpg" },
    // { image: "/Fotky/Natery fasad (6).jpg" },
    // { image: "/Fotky/Realizace (4).jpg" }
];