export const GalleryItems = [
    { image: "/Fotky/hero/hero-1.avif", },
    { image: "/Fotky/malovani-detskeho-pokoje/malovani-detskeho-pokoje-1.avif" },
    { image: "/Fotky/malovani-detskeho-pokoje/malovani-detskeho-pokoje-2.avif" },
    { image: "/Fotky/malovani-detskeho-pokoje/malovani-detskeho-pokoje-3.avif" },
    { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-1.avif" },
    { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-2.avif" },
    { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-3.avif" },
    { image: "/Fotky/malovani-loznice/malovani-loznice-1.avif" },
    { image: "/Fotky/malovani-loznice/malovani-loznice-2.avif" },
    { image: "/Fotky/malovani-loznice/malovani-loznice-3.avif" },
    { image: "/Fotky/malovani-na-klic/malovani-na-klic-1.avif" },
    { image: "/Fotky/malovani-na-klic/malovani-na-klic-2.avif" },
    { image: "/Fotky/malovani-na-klic/malovani-na-klic-3.avif" },
    { image: "/Fotky/uklid-po-malovani/uklid-po-malovani-1.avif" },
    { image: "/Fotky/uklid-po-malovani/uklid-po-malovani-3.avif" },
];