export const GalleryItems = [
    // { image: "/Fotky/hero/hero-1.avif", },
    // { image: "/Fotky/malovani-detskeho-pokoje/malovani-detskeho-pokoje-1.avif" },
    // { image: "/Fotky/malovani-detskeho-pokoje/malovani-detskeho-pokoje-2.avif" },
    // { image: "/Fotky/malovani-detskeho-pokoje/malovani-detskeho-pokoje-3.avif" },
    // { image: "/Fotky/malovani-detskeho-pokoje/malovani-detskeho-pokoje-4.avif" },
    // { image: "/Fotky/malovani-detskeho-pokoje/malovani-detskeho-pokoje-5.avif" },
    // { image: "/Fotky/malovani-detskeho-pokoje/malovani-detskeho-pokoje-6.avif" },
    // { image: "/Fotky/malovani-detskeho-pokoje/malovani-detskeho-pokoje-7.avif" },
    // { image: "/Fotky/malovani-detskeho-pokoje/malovani-detskeho-pokoje-8.avif" },
    // { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-1.avif" },
    // { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-2.avif" },
    // { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-3.avif" },
    // { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-4.avif" },
    // { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-5.avif" },
    // { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-6.avif" },
    // { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-7.avif" },
    // { image: "/Fotky/malovani-kuchyne/malovani-kuchyne-8.avif" },
    // { image: "/Fotky/malovani-loznice/malovani-loznice-1.avif" },
    // { image: "/Fotky/malovani-loznice/malovani-loznice-2.avif" },
    // { image: "/Fotky/malovani-loznice/malovani-loznice-3.avif" },
    // { image: "/Fotky/malovani-loznice/malovani-loznice-4.avif" },
    // { image: "/Fotky/malovani-loznice/malovani-loznice-5.avif" },
    // { image: "/Fotky/malovani-loznice/malovani-loznice-6.avif" },
    // { image: "/Fotky/malovani-loznice/malovani-loznice-7.avif" },
    // { image: "/Fotky/malovani-loznice/malovani-loznice-8.avif" },
    // { image: "/Fotky/malovani-na-klic/malovani-na-klic-1.avif" },
    // { image: "/Fotky/malovani-na-klic/malovani-na-klic-2.avif" },
    // { image: "/Fotky/malovani-na-klic/malovani-na-klic-3.avif" },
    // { image: "/Fotky/malovani-na-klic/malovani-na-klic-4.avif" },
    // { image: "/Fotky/malovani-na-klic/malovani-na-klic-5.avif" },
    // { image: "/Fotky/malovani-na-klic/malovani-na-klic-6.avif" },
    // { image: "/Fotky/malovani-na-klic/malovani-na-klic-7.avif" },
    // { image: "/Fotky/malovani-na-klic/malovani-na-klic-8.avif" },
    // { image: "/Fotky/uklid-po-malovani/uklid-po-malovani-1.avif" },
    // { image: "/Fotky/uklid-po-malovani/uklid-po-malovani-2.avif" },
    // { image: "/Fotky/uklid-po-malovani/uklid-po-malovani-3.avif" },
    // { image: "/Fotky/uklid-po-malovani/uklid-po-malovani-4.avif" },
    // { image: "/Fotky/uklid-po-malovani/uklid-po-malovani-5.avif" },

    { image: "/Fotky/galerie/galerie-1.avif" },
    { image: "/Fotky/galerie/galerie-2.avif" },
    { image: "/Fotky/galerie/galerie-3.avif" },
    { image: "/Fotky/galerie/galerie-4.avif" },
    { image: "/Fotky/galerie/galerie-5.avif" },
    { image: "/Fotky/galerie/galerie-6.avif" },
    { image: "/Fotky/galerie/galerie-7.avif" },
    { image: "/Fotky/galerie/galerie-8.avif" },
    { image: "/Fotky/galerie/galerie-9.avif" },
    { image: "/Fotky/galerie/galerie-10.avif" },
    { image: "/Fotky/galerie/galerie-11.avif" },
    { image: "/Fotky/galerie/galerie-12.avif" },
    { image: "/Fotky/galerie/galerie-13.avif" },
    { image: "/Fotky/galerie/galerie-14.avif" },
    { image: "/Fotky/galerie/galerie-15.avif" },
    { image: "/Fotky/galerie/galerie-16.avif" },
    { image: "/Fotky/galerie/galerie-17.avif" },
    { image: "/Fotky/galerie/galerie-18.avif" },
    { image: "/Fotky/galerie/galerie-19.avif" },
    { image: "/Fotky/galerie/galerie-20.avif" },
    { image: "/Fotky/galerie/galerie-21.avif" },
    { image: "/Fotky/galerie/galerie-22.avif" },
    { image: "/Fotky/galerie/galerie-23.avif" },
    { image: "/Fotky/galerie/galerie-24.avif" },
    { image: "/Fotky/galerie/galerie-25.avif" },
    { image: "/Fotky/galerie/galerie-26.avif" },
    { image: "/Fotky/galerie/galerie-27.avif" },
    { image: "/Fotky/galerie/galerie-28.avif" },
    { image: "/Fotky/galerie/galerie-29.avif" },
    { image: "/Fotky/galerie/galerie-30.avif" },
    { image: "/Fotky/galerie/galerie-31.avif" },
    { image: "/Fotky/galerie/galerie-32.avif" },
    { image: "/Fotky/galerie/galerie-33.avif" },
    { image: "/Fotky/galerie/galerie-34.avif" },
    { image: "/Fotky/galerie/galerie-35.avif" },
    { image: "/Fotky/galerie/galerie-36.avif" },
    { image: "/Fotky/galerie/galerie-37.avif" },
    { image: "/Fotky/galerie/galerie-38.avif" },
    { image: "/Fotky/galerie/galerie-39.avif" },
    { image: "/Fotky/galerie/galerie-40.avif" },
    { image: "/Fotky/galerie/galerie-41.avif" },
    { image: "/Fotky/galerie/galerie-42.avif" },
    { image: "/Fotky/galerie/galerie-43.avif" },
    { image: "/Fotky/galerie/galerie-44.avif" },
    { image: "/Fotky/galerie/galerie-45.avif" },
    { image: "/Fotky/galerie/galerie-46.avif" },
    { image: "/Fotky/galerie/galerie-47.avif" },
    { image: "/Fotky/galerie/galerie-48.avif" },
    { image: "/Fotky/galerie/galerie-49.avif" },
    { image: "/Fotky/galerie/galerie-50.avif" },
    { image: "/Fotky/galerie/galerie-51.avif" },
    { image: "/Fotky/galerie/galerie-52.avif" },
    { image: "/Fotky/galerie/galerie-53.avif" },
    { image: "/Fotky/galerie/galerie-54.avif" },
    { image: "/Fotky/galerie/galerie-55.avif" },
    { image: "/Fotky/galerie/galerie-56.avif" },
    { image: "/Fotky/galerie/galerie-57.avif" },
    { image: "/Fotky/galerie/galerie-58.avif" },
    { image: "/Fotky/galerie/galerie-59.avif" },
    { image: "/Fotky/galerie/galerie-60.avif" },
    { image: "/Fotky/galerie/galerie-61.avif" },
    { image: "/Fotky/galerie/galerie-62.avif" },
    { image: "/Fotky/galerie/galerie-63.avif" },
    { image: "/Fotky/galerie/galerie-64.avif" },
    { image: "/Fotky/galerie/galerie-65.avif" },
    { image: "/Fotky/galerie/galerie-66.avif" },
    { image: "/Fotky/galerie/galerie-67.avif" },
    { image: "/Fotky/galerie/galerie-68.avif" }
];