export const GalleryItems = [
    { image: "/Fotky/Hero (1).jpg", },
    { image: "/Fotky/Malovani (1).jpg" },
    { image: "/Fotky/Malovani (2).jpg" },
    { image: "/Fotky/Malovani (3).jpg" },
    { image: "/Fotky/Malovani (4).jpg" },
    { image: "/Fotky/Malovani na klic (1).jpg" },
    { image: "/Fotky/Malovani na klic (2).jpg" },
    { image: "/Fotky/Malovani na klic (3).jpg" },
    { image: "/Fotky/Malovani na klic (4).jpg" },
    { image: "/Fotky/Malovani na klic (5).jpg" },
    { image: "/Fotky/Nater dveri (1).jpg" },
    { image: "/Fotky/Nater oken (1).jpg" },
    { image: "/Fotky/Natery fasad (5).jpg" },
    { image: "/Fotky/Natery fasad (7).jpg" },
    { image: "/Fotky/Natery fasad (6).jpg" },
    { image: "/Fotky/Realizace (4).jpg" },
    { image: "/Fotky/Natery strech (6).jpg" },
    { image: "/Fotky/Realizace (1).jpg" },
    { image: "/Fotky/Realizace (2).jpg" },
    { image: "/Fotky/Realizace (3).jpg" },
    { image: "/Fotky/Realizace (5).jpg" },
    { image: "/Fotky/Realizace (6).jpg" },
    { image: "/Fotky/Nastrik radiatoru (7).jpg" },
    { image: "/Fotky/Natery fasad (1).jpg" }
];